const modules=[
{id:1,phase:'space',title:'Notice the hidden payoff of busy',sub:'Busyness can signal status, numb discomfort, and postpone hard questions.',summary:'White space is not laziness. It is the mental room required to notice what matters and make deliberate choices.',points:['A packed schedule may be partly externally imposed—and partly reinforced by identity, status, or emotional avoidance.','Execution mode feels safe because the next task is clear; strategic questions are uncertain and uncomfortable.','Reframe chronic busyness as loss of control, not proof of importance.','Use the calendar—not an endless task list—to reserve priorities and constrain work.','You do not need a retreat. Even a little protected mental space can improve decisions.'],prompt:'What question might your busyness be helping you avoid?'},
{id:2,phase:'space',title:'Say no—even to good things',sub:'Every yes spends time, energy, attention, and an alternative future.',summary:'Selectivity changes by season. Early exploration may require more yeses; growing responsibility requires stronger filters.',points:['The hardest choices are not good versus bad, but good versus more aligned.','Count the total time, opportunity cost, and physical or emotional cost—not just the visible event.','Ask whether you will regret declining in one, five, or ten years.','Request more details before committing; vague or poorly prepared requests often disappear.','Choose what you are willing to be bad at. Excellence requires not doing everything.'],prompt:'What good opportunity may be crowding out something more important?'},
{id:3,phase:'focus',title:'Set goals that are truly yours',sub:'When purpose is unclear, optimize for what is genuinely interesting.',summary:'Money and meaning are not the only goal filters. Curiosity offers useful evidence and can lead toward mastery, contribution, and unexpected opportunities.',points:['Notice how you voluntarily spend time; behavior often reveals interest more reliably than abstract declarations.','Reconnect with why you entered a field before deciding whether to leave it.','A nonlinear experience can still build a distinctive combination of skills and stories.','Ask what kind of person an experience would help you become.','Think bigger than what is possible today; pair a remarkable direction with small, consistent action.'],prompt:'If nobody could judge the answer, what would you want to explore?'},
{id:4,phase:'focus',title:'Create protected exploration time',sub:'Use a small portfolio of experiments before making an all-in bet.',summary:'“20% time” is a principle, not a rigid quota: protect a meaningful minority of your capacity for learning, side projects, and low-risk tests.',points:['Seek development opportunities proactively; they are rarely handed to you.','Experiment while your core position is stable, before desperation forces a rushed pivot.','Use little bets to test enjoyment, aptitude, demand, and impact.','Design every experiment so you can win even if the main outcome fails—through skills, relationships, evidence, or insight.','Add structure: state the goal, find a teacher or peer, set a date, and keep a learning loop.'],prompt:'What could you test in two hours without needing permission?'},
{id:5,phase:'focus',title:'Think in waves',sub:'Sequence priorities instead of trying to maximize everything at once.',summary:'Long careers move through recurring waves: Learning, Creating, Connecting, and Reaping. Each matters, but not equally in every season.',points:['Alternate heads-up exploration with heads-down execution.','Learning builds mastery; Creating turns knowledge into visible contribution.','Connecting embeds you in a community of exchange and opportunity.','Reaping lets you benefit from credibility, demand, and accumulated work.','Do not remain in one wave forever. Revisit learning before success becomes stagnation.'],prompt:'Which wave are you in—and which neglected wave will matter next?'},
{id:6,phase:'focus',title:'Build strategic leverage',sub:'Make the same unit of effort travel farther.',summary:'Leverage is thoughtful multiplication: focus on high-yield work, design assets that can be reused, and exchange the resources you already possess.',points:['Identify the small share of activities producing most meaningful results.','Stop low-value work and use constraints to improve systems.','Ask how one action can count ten times—for example, turning research into a talk, article, and workshop.','Name your hypotheses about the future and place modest bets consistent with them.','Recognize multiple currencies: time, expertise, trust, audience, access, reputation, and location flexibility.'],prompt:'What are you doing repeatedly that could become one reusable system or asset?'},
{id:7,phase:'focus',title:'Choose the right people and rooms',sub:'Build relationships on interest and reciprocity, not extraction.',summary:'The strongest networks develop before a need arises. Go deep in a few communities and make the relationship valuable in both directions.',points:['Short-term networking meets an immediate need; use it sparingly and with established relationships.','Long-term networking develops genuine connections with people you admire.','Infinite-horizon networking follows fascination across fields with no expected payoff.','Try “no asks for a year” with new connections to remove transactional pressure.','When joining a group, participate deeply. Offer value creatively, including outside the other person’s main field.'],prompt:'Who would be interesting to know even if they could never advance your career?'},
{id:8,phase:'faith',title:'Practice strategic patience',sub:'Slow visible progress does not automatically mean the strategy is wrong.',summary:'Meaningful recognition often has a long runway. Look for raindrops—small signs that effort is beginning to compound—and use informed advisers to calibrate.',points:['In many fields, noticeable signals may take two or three years; deep credibility can take five or more.','Distinguish “not yet” from “not working” by learning the real timeline from people who have done it.','Track leading indicators—skills, output, responses, invitations—not only major outcomes.','Reconnect with why you chose the goal and examine how the pathway worked for others.','Use trusted, knowledgeable advisers—not vanity metrics alone—to decide whether to persist or pivot.'],prompt:'What small “raindrop” of progress have you been discounting?'},
{id:9,phase:'faith',title:'Turn failure into experiments',sub:'A rejected route is not the same as a rejected destination.',summary:'Excellent work still encounters chance and gatekeepers. Increase your at-bats, test cheaply, preserve what you learned, and keep multiple paths open.',points:['If every goal succeeds, the goals may be too safe.','Quality matters, but so does the number of chances you give quality to be noticed.','Run small tests before full investment so an unwanted result becomes information.','Repurpose assets, skills, and connections from plans that did not work.','Strengthen commitment with a date and appropriate involvement from other people.'],prompt:'What “failure” could you rename as data from an experiment?'},
{id:10,phase:'faith',title:'Let the work compound',sub:'Delay gratification without postponing all joy.',summary:'Long-term thinkers begin very small, understand the actual runway, constrain effort intelligently, and keep moving through inevitable discomfort.',points:['Comparison uses somebody else’s timeline and visible outcomes as your private yardstick.','Starting small creates momentum and evidence; the whole goal does not need to be solved today.','Research what the path really requires so you can pace yourself realistically.','Bounded work time can force better choices and systems.','A longer horizon enables you to tolerate fluctuations and pursue outcomes others abandon too soon.'],prompt:'What five-minute action would count as beginning?'},
];
const keys=modules.flatMap(m=>m.points.slice(0,3).map((p,i)=>({tag:`MODULE ${m.id}`,title:i===0?m.title:['Practice','Remember'][i-1]||'Key idea',text:p}))).concat([
{tag:'CORE',title:'Independence',text:'Choose from an internal compass when applause, certainty, and conventional validation are absent.'},{tag:'CORE',title:'Curiosity',text:'Treat attention and fascination as clues; exploration can precede certainty.'},{tag:'CORE',title:'Resilience',text:'Assume the route may change. Prepare alternatives and keep creating chances to succeed.'}
]);
const state=JSON.parse(localStorage.getItem('futureByDesignState')||'{"done":[],"notes":{}}');
const save=()=>localStorage.setItem('futureByDesignState',JSON.stringify(state));
const grid=document.querySelector('#moduleGrid'), dialog=document.querySelector('#moduleDialog'), content=document.querySelector('#dialogContent');
function renderModules(phase='all'){grid.innerHTML=modules.filter(m=>phase==='all'||m.phase===phase).map(m=>`<button class="module-card ${state.done.includes(m.id)?'done':''}" data-id="${m.id}"><span class="num">${String(m.id).padStart(2,'0')}</span><span><h3>${m.title}</h3><p>${m.sub}</p></span><span class="check">${state.done.includes(m.id)?'✓':'→'}</span></button>`).join('');grid.querySelectorAll('button').forEach(b=>b.onclick=()=>openModule(+b.dataset.id));}
function openModule(id){const m=modules.find(x=>x.id===id);content.innerHTML=`<span class="lesson-tag">MODULE ${m.id} OF 10</span><h2>${m.title}</h2><p class="lead">${m.summary}</p><ul class="lesson-points">${m.points.map(p=>`<li>${p}</li>`).join('')}</ul><div class="reflection"><label><strong>Pause and reflect</strong><p>${m.prompt}</p><textarea id="moduleNote" placeholder="Write a private note…">${state.notes['module-'+id]||''}</textarea></label></div><div class="dialog-actions"><button class="button ghost" id="prevModule" ${id===1?'disabled':''}>← Previous</button><button class="button primary" id="completeModule">${state.done.includes(id)?'Completed ✓':'Mark complete'}</button><button class="button ghost" id="nextModule" ${id===10?'disabled':''}>Next →</button></div>`;dialog.showModal();document.querySelector('#moduleNote').oninput=e=>{state.notes['module-'+id]=e.target.value;save()};document.querySelector('#completeModule').onclick=()=>{if(!state.done.includes(id))state.done.push(id);save();updateProgress();renderModules(document.querySelector('.phase.active').dataset.phase);openModule(id)};if(id>1)document.querySelector('#prevModule').onclick=()=>openModule(id-1);if(id<10)document.querySelector('#nextModule').onclick=()=>openModule(id+1);}
function updateProgress(){const pct=state.done.length*10;document.querySelector('#progressText').textContent=pct+'%';document.querySelector('#progressBar').style.width=pct+'%'}
document.querySelectorAll('.phase').forEach(b=>b.onclick=()=>{document.querySelector('.phase.active').classList.remove('active');b.classList.add('active');renderModules(b.dataset.phase)});
document.querySelector('#closeDialog').onclick=()=>dialog.close();document.querySelector('#resetBtn').onclick=()=>{if(confirm('Clear module progress and all saved reflections?')){state.done=[];state.notes={};save();renderModules();updateProgress();bindNotes()}};
function bindNotes(){document.querySelectorAll('[data-note]').forEach(el=>{el.value=state.notes[el.dataset.note]||'';el.oninput=()=>{state.notes[el.dataset.note]=el.value;save()}})}
const criteria=[['Excitement',1],['Long-term fit',1],['Opportunity cost',-1],['Energy cost',-1]];document.querySelector('#decisionTool').innerHTML=criteria.map(([n])=>`<div class="slider"><label>${n} <output>3</output><input aria-label="${n}" type="range" min="1" max="5" value="3"></label></div>`).join('');function scoreDecision(){const vals=[...document.querySelectorAll('.slider input')].map(x=>+x.value);document.querySelectorAll('.slider output').forEach((o,i)=>o.textContent=vals[i]);const score=vals[0]+vals[1]+(6-vals[2])+(6-vals[3]);document.querySelector('#decisionScore').textContent=score+'/20';document.querySelector('#decisionAdvice').textContent=score>=16?'Strong signal: explore a deliberate yes—after confirming the full commitment.':score>=11?'Mixed signal: ask for details, negotiate scope, or wait 24 hours.':'Protect the space: this may be a thoughtful no, delegation, or “not now.”'}document.querySelectorAll('.slider input').forEach(x=>x.oninput=scoreDecision);scoreDecision();
const waves={Learning:'Study the craft. Find models, teachers, deliberate practice, and foundational experience.',Creating:'Turn what you know into useful output. Share ideas, prototypes, services, or art.',Connecting:'Contribute to a few communities deeply. Build mutual relationships before you need them.',Reaping:'Accept the return on accumulated work—income, reach, influence, or choice—then plan your next learning cycle.'};document.querySelector('#waveTool').innerHTML=Object.keys(waves).map(w=>`<button>${w}</button>`).join('');document.querySelectorAll('#waveTool button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#waveTool button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#waveAdvice').textContent=waves[b.textContent]});
function renderKeys(q=''){const s=q.toLowerCase();document.querySelector('#keyGrid').innerHTML=keys.filter(k=>(k.title+' '+k.text+' '+k.tag).toLowerCase().includes(s)).map(k=>`<article class="key-card"><span>${k.tag}</span><h3>${k.title}</h3><p>${k.text}</p></article>`).join('')||'<p>No matches. Try a broader term.</p>'}document.querySelector('#searchInput').oninput=e=>renderKeys(e.target.value);
const questions=[{q:'Which response best represents long-term thinking?',a:['Predict one fixed future perfectly','Choose a direction and learn through small bets','Keep every option open forever'],correct:1,why:'A long horizon is compatible with flexibility: direction plus experiments creates options.'},{q:'What is the purpose of “20% time”?',a:['Work 20% longer','Guarantee a profitable side project','Protect capacity for low-risk exploration'],correct:2,why:'The point is a bounded, meaningful experiment—not a guaranteed result or extra overload.'},{q:'Which is infinite-horizon networking?',a:['Meeting someone fascinating with no expected payoff','Contacting a stranger for an urgent referral','Collecting as many contacts as possible'],correct:0,why:'It begins with genuine interest in the person, without an instrumental ask.'},{q:'What should follow a failed route?',a:['Abandon the destination immediately','Hide the attempt','Extract learning and test another path'],correct:2,why:'Routes can fail while the larger direction remains sound.'}];let qi=0,qs=0;function renderQuiz(){const box=document.querySelector('#quizBox');if(qi>=questions.length){box.innerHTML=`<h3>You got ${qs} of ${questions.length}</h3><p>${qs===questions.length?'Excellent recall. Now choose one idea to practice.':'Review the modules that felt least familiar, then try again.'}</p><button class="button primary" id="again">Try again</button>`;document.querySelector('#again').onclick=()=>{qi=0;qs=0;renderQuiz()};return}const x=questions[qi];box.innerHTML=`<p class="eyebrow">QUESTION ${qi+1} / ${questions.length}</p><h3>${x.q}</h3><div class="quiz-options">${x.a.map((a,i)=>`<button data-i="${i}">${a}</button>`).join('')}</div><div class="feedback" aria-live="polite"></div>`;box.querySelectorAll('.quiz-options button').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===x.correct;if(ok)qs++;box.querySelector('.feedback').innerHTML=`${ok?'✓ Correct.':'Not quite.'} ${x.why} <button class="button ghost" id="continue">Continue</button>`;box.querySelectorAll('.quiz-options button').forEach(x=>x.disabled=true);document.querySelector('#continue').onclick=()=>{qi++;renderQuiz()}})}
const steps=['Block 20 minutes of unscheduled thinking time.','Decline or defer one low-value request.','Write down three things you are genuinely curious about.','Schedule one tiny experiment on your calendar.','Name your current wave: Learning, Creating, Connecting, or Reaping.','Turn one repeated task into a reusable template.','Send a no-ask note of appreciation to someone interesting.','List one small raindrop of progress.','Give a disappointing outcome a new name: data.','Take five minutes toward a goal that matters.'];const quick=document.querySelector('#quickDialog');document.querySelector('#quickBtn').onclick=()=>{document.querySelector('#quickStep').textContent=steps[Math.floor(Math.random()*steps.length)];quick.showModal()};document.querySelector('#closeQuick').onclick=()=>quick.close();
const clean=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function printAnswer(key){const value=(state.notes[key]||'').trim();return `<div class="print-answer ${value?'':'empty'}">${value?clean(value):'Space for your response'}</div>`}
function buildPrintView(){
  document.querySelectorAll('[data-note]').forEach(el=>state.notes[el.dataset.note]=el.value);
  save();
  const selectedWave=document.querySelector('#waveTool button.active')?.textContent||'';
  const moduleNotes=modules.filter(m=>(state.notes['module-'+m.id]||'').trim()).map(m=>`<article class="print-reflection"><h3>${String(m.id).padStart(2,'0')} · ${m.title}</h3><p class="print-prompt">${m.prompt}</p>${printAnswer('module-'+m.id)}</article>`).join('');
  document.querySelector('#printView').innerHTML=`<section class="print-cover"><p class="print-kicker">Personal reflection workbook</p><h1>Future by Design</h1><p class="print-lead">A practical record of the direction you are choosing, the experiments you are running, and the next small steps you want to take.</p><p class="print-meta">Prepared ${new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}</p></section><section class="print-section"><h2>My future-building plan</h2><p class="print-section-intro">Direction matters more than perfect prediction.</p><article class="print-entry"><h3>In 5–10 years, I want more…</h3>${printAnswer('direction')}</article><article class="print-entry"><h3>My priority for the next 90 days</h3>${printAnswer('priority')}</article><article class="print-entry"><h3>My next small, scheduled step</h3>${printAnswer('next-step')}</article>${selectedWave?`<article class="print-entry"><h3>My current wave</h3><div class="print-answer">${clean(selectedWave)}</div></article>`:''}</section><section class="print-section"><h2>My 20% experiment</h2><p class="print-section-intro">A small test can create learning without requiring an all-in commitment.</p><article class="print-entry"><h3>Something I am curious about</h3>${printAnswer('experiment')}</article><article class="print-entry"><h3>The smallest test I can run</h3>${printAnswer('experiment-test')}</article><article class="print-entry"><h3>How I still win if the test fails</h3>${printAnswer('experiment-win')}</article></section>${moduleNotes?`<section class="print-section"><h2>Module reflections</h2><p class="print-section-intro">The notes I chose to capture while moving through the guide.</p>${moduleNotes}</section>`:''}<div class="print-footer"><span>Future by Design · Personal worksheet</span><span>Developed by <a href="https://mindx.us/">Mind X Associates</a></span></div>`;
}
window.addEventListener('beforeprint',buildPrintView);document.querySelector('#printBtn').onclick=()=>{buildPrintView();window.print()};document.querySelector('#menuBtn').onclick=e=>{const nav=document.querySelector('#nav');const isOpen=nav.classList.toggle('open');e.target.setAttribute('aria-expanded',isOpen)};document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>{document.querySelector('#nav').classList.remove('open');document.querySelector('#menuBtn').setAttribute('aria-expanded','false')});
renderModules();renderKeys();renderQuiz();bindNotes();updateProgress();