const modules=[
{id:1,phase:'space',title:'洞察“忙碌”背后的隐性收益',sub:'忙碌可能是一种身份象征，也可能是对不安的麻木和对难题的逃避。',summary:'留白绝非懒惰，而是让你关注重要事物、做出明智选择所必需的心智空间。',points:['充实的日程安排，一部分可能源于外界的强制要求，但也可能受到了身份认同、社会地位或情感逃避的推波挽浪。','执行模式让人感到安全，因为下一个任务清晰明确；而战略层面的思考则充满不确定性，令人感到不适。','重新审视慢性忙碌：它并非重要性的证明，而是失去掌控力的表现。','使用日历（而非无休止的任务清单）来预留优先事项并限制工作时长。','你不需要专门去静修。即便是微小且受保护的心智空间，也能显著提升决策质量。'],prompt:'你的忙碌，可能正在帮你逃避什么问题？'},
{id:2,phase:'space',title:'学会拒绝——即便面对好的机会',sub:'每一次顺应，都在消耗你的时间、精力、专注力以及另一种未来的可能性。',summary:'选择标准因阶段而异。早期的探索可能需要更多的尝试；而随着责任的增长，则需要更严格的筛选。',points:['最艰难的选择往往不是“好与坏”的选择，而是“好与更契合”之间的权衡。','算清总成本：包括时间、机会成本以及身心消耗，而不仅仅是显而易见的事件本身。','问问自己：如果在一年、五年或十年后拒绝这件事，自己是否会后悔。','在作出承诺前获取更多细节；模糊或准备不足的请求往往会自动消失。','主动选择你愿意“表现平平”的领域。卓越的前提是学会不包揽一切。'],prompt:'眼前有什么不错的机会，可能正在挤占更重要的事情？'},
{id:3,phase:'focus',title:'设定真正属于你的目标',sub:'当目标不够清晰时，不妨专注于那些能引发你真正兴趣的事物。',summary:'金钱和意义并非唯一的决策标准。好奇心是极具价值的线索，能引导你走向精通、贡献以及意料之外的机遇。',points:['注意你自发投入时间的地方；相比于抽象的口号，行为能更真实地揭示你的兴趣所在。','在决定离开一个领域之前，先重温当初选择进入它的初心。','非线性的履历同样可以磨砺出独特的技能组合与人生故事。','思考某种经历能帮助你成为什么样的人。','敢于超越当下的可能性去思考；将远大的方向与微小、持续的行动相结合。'],prompt:'如果不受任何人的评判，你最想探索什么？'},
{id:4,phase:'focus',title:'打造受保护的探索时间',sub:'在倾尽全力之前，先通过一小部分实验组合进行测试。',summary:'“20% 时间”是一项原则，而非死板的配额：保护一小部分核心精力，用于学习、副业项目和低风险测试。',points:['主动寻找成长机会；这些机会很少会被主动送到你面前。','在主业稳定的状态下进行实验，避免迫于无奈而仓促转型。','通过微型尝试来测试兴趣度、胜任力、市场需求及实际影响。','设计好每一次实验，即便主要结果不如预期，也能通过积累技能、人脉、证据或洞察实现获益。','增加结构感：明确目标、寻找导师或同行、设定截止日期，并建立学习反馈闭环。'],prompt:'无需寻求批准，你在两小时内可以测试什么？'},
{id:5,phase:'focus',title:'学会像波浪一样思考',sub:'对优先事项进行排序和分阶段推进，而不是试图同时做好所有事情。',summary:'漫长的职业生涯就像不断循环的波浪：学习、创造、链接、收获。每一阶段都不可或缺，但并非在每个时期都同等重要。',points:['交替进行“抬头探索”与“埋头执行”。','学习能积累专业能力；创造能将知识转化为可见的贡献。','链接能让你融入相互赋能与充满机遇的社区。','收获能让你从建立的声誉、市场需求和积累的成果中受益。','不要永远停留在一个阶段。在成功沦为停滞之前，重新回到学习阶段。'],prompt:'你目前正处于哪一波浪潮中？下一个被忽视但至关重要的浪潮又是什么？'},
{id:6,phase:'focus',title:'构建战略杠杆',sub:'让单位精力发挥更大的价值。',summary:'杠杆是经过深思熟虑的放大效应：专注于高回报的工作，设计可复用的资产，并交换你已拥有的资源。',points:['识别出那小部分能带来最显著成果的核心活动。','停止低价值的工作，利用约束条件来优化系统。','思考如何让一次行动产生十倍的效益——例如将一项研究转化为演讲、文章和工作坊。','明确你对未来的假设，并进行与之相符的适度投入。','认识到多种资源价值：时间、专业知识、信任、受众、资源渠道、声誉和地理灵活性。'],prompt:'有什么事情是你一直在重复做的，可以将其转化为可复用的系统或资产？'},
{id:7,phase:'focus',title:'选择对的人与社交圈',sub:'基于共同兴趣和互惠互利建立关系，而非单方面的索取。',summary:'最坚固的人脉网络建立于需求产生之前。深耕少数优质社区，让人脉关系实现双向赋能。',points:['短期社交旨在满足眼前的需求；应谨慎使用，且仅限建立在既有关系之上。','长期社交是在你所钦佩的人之间建立真诚的连接。','无限视野社交则是跨越领域、不求即时回报地追随你的兴趣所在。','尝试与新结识的人建立“一年内不提出请求”的约定，消除功利色彩。','加入一个群体时要深度参与。创造性地提供价值，包括对方核心领域之外的帮助。'],prompt:'即便对方永远无法对你的事业有所助力，你依然觉得认识谁会很有趣？'},
{id:8,phase:'faith',title:'保持战略定力',sub:'显性进展缓慢，并不意味着战略本身是错误的。',summary:'意义非凡的认可往往需要较长的孕育期。学会捕捉“雨滴”——那些表明努力开始产生复利效应的微小信号，并借助睿智的顾问进行评估调整。',points:['在许多领域，显著的信号可能需要两三年的时间；而深厚的公信力则可能需要五年甚至更久。','向有经验的人请教真实的成长周期，从而区分“尚未显现”与“行不通”。','追踪领先指标——技能提升、产出成果、反馈回应、受邀机会——而不仅仅关注最终的大结果。','重新审视你选择该目标的初心，并研究这一路径在他人身上是如何奏效的。','依靠值得信赖且具专业知识的顾问（而非仅看表面数据）来决定是坚持还是转型。'],prompt:'有哪些微小的成长“雨滴”，一直被你轻视了？'},
{id:9,phase:'faith',title:'将失败转化为实验',sub:'被否决的路径，不等于被否决的目标。',summary:'优秀的作品同样会遭遇偶然性与门槛限制。增加尝试次数、降低测试成本、保留经验教训，并保持多条路径通畅。',points:['如果每一个目标都能顺利实现，那说明目标设定得太过于安全了。','质量固然重要，但给质量提供被认可的机会次数同样关键。','在全力投入之前先进行小规模测试，这样即使结果不如预期，也能转化为宝贵的资料信息。','将未达预期的计划中所沉淀的资产、技能和人脉重新利用起来。','通过设定明确日期和引入外部监督，来强化你的承诺和执行力。'],prompt:'有哪些“失败”，可以被你重新定义为实验数据？'},
{id:10,phase:'faith',title:'让努力产生复利效应',sub:'延迟满足，并不意味着要剥夺过程中的所有快乐。',summary:'长期主义者懂得从小处着手，理解真实的成长周期，明智地约束精力投入，并在必然的不适感中持续前行。',points:['盲目对比是将他人的时间线和表面成果，当成了测量自己的私人尺码。','从小处着手能创造势能和证据；你不需要在今天解决整个终极目标。','深入研究路径的实际要求，以便合理安排自己的节奏。','有限的工作时间能够倒逼出更好的选择和系统。','更长远视角能让你包容起伏，坚持追求那些他人过早放弃的成果。'],prompt:'现在采取什么只需 5 分钟的行动，可以算作是一个良好的开端？'},
];
const keys=modules.flatMap(m=>m.points.slice(0,3).map((p,i)=>({tag:`模块 ${m.id}`,title:i===0?m.title:['实践','记住'][i-1]||'核心要点',text:p}))).concat([
{tag:'核心',title:'独立',text:'当缺乏掌声、确定性和传统认可时，依据内心笃定的罗盘做出选择。'},{tag:'核心',title:'好奇',text:'将专注力和着迷视为线索；探索可以先于确定性发生。'},{tag:'核心',title:'韧性',text:'做好路径随时可能改变的准备。预备替代方案，并不断创造成功的机会。'}
]);
const state=JSON.parse(localStorage.getItem('futureByDesignState')||'{"done":[],"notes":{}}');
const save=()=>localStorage.setItem('futureByDesignState',JSON.stringify(state));
const grid=document.querySelector('#moduleGrid'), dialog=document.querySelector('#moduleDialog'), content=document.querySelector('#dialogContent');
function renderModules(phase='all'){grid.innerHTML=modules.filter(m=>phase==='all'||m.phase===phase).map(m=>`<button class="module-card ${state.done.includes(m.id)?'done':''}" data-id="${m.id}"><span class="num">${String(m.id).padStart(2,'0')}</span><span><h3>${m.title}</h3><p>${m.sub}</p></span><span class="check">${state.done.includes(m.id)?'✓':'→'}</span></button>`).join('');grid.querySelectorAll('button').forEach(b=>b.onclick=()=>openModule(+b.dataset.id));}
function openModule(id){const m=modules.find(x=>x.id===id);content.innerHTML=`<span class="lesson-tag">模块 ${m.id} / 10</span><h2>${m.title}</h2><p class="lead">${m.summary}</p><ul class="lesson-points">${m.points.map(p=>`<li>${p}</li>`).join('')}</ul><div class="reflection"><label><strong>停下来思考</strong><p>${m.prompt}</p><textarea id="moduleNote" placeholder="写下你的私人心得…">${state.notes['module-'+id]||''}</textarea></label></div><div class="dialog-actions"><button class="button ghost" id="prevModule" ${id===1?'disabled':''}>← 上一模块</button><button class="button primary" id="completeModule">${state.done.includes(id)?'已完成 ✓':'标记为完成'}</button><button class="button ghost" id="nextModule" ${id===10?'disabled':''}>下一模块 →</button></div>`;dialog.showModal();document.querySelector('#moduleNote').oninput=e=>{state.notes['module-'+id]=e.target.value;save()};document.querySelector('#completeModule').onclick=()=>{if(!state.done.includes(id))state.done.push(id);save();updateProgress();renderModules(document.querySelector('.phase.active').dataset.phase);openModule(id)};if(id>1)document.querySelector('#prevModule').onclick=()=>openModule(id-1);if(id<10)document.querySelector('#nextModule').onclick=()=>openModule(id+1);}
function updateProgress(){const pct=state.done.length*10;document.querySelector('#progressText').textContent=pct+'%';document.querySelector('#progressBar').style.width=pct+'%'}
document.querySelectorAll('.phase').forEach(b=>b.onclick=()=>{document.querySelector('.phase.active').classList.remove('active');b.classList.add('active');renderModules(b.dataset.phase)});
document.querySelector('#closeDialog').onclick=()=>dialog.close();document.querySelector('#resetBtn').onclick=()=>{if(confirm('确定要清空模块进度和所有已保存的心得吗？')){state.done=[];state.notes={};save();renderModules();updateProgress();bindNotes()}};
function bindNotes(){document.querySelectorAll('[data-note]').forEach(el=>{el.value=state.notes[el.dataset.note]||'';el.oninput=()=>{state.notes[el.dataset.note]=el.value;save()}})}
const criteria=[['兴奋程度',1],['长期契合度',1],['机会成本',-1],['精力消耗',-1]];document.querySelector('#decisionTool').innerHTML=criteria.map(([n])=>`<div class="slider"><label>${n} <output>3</output><input aria-label="${n}" type="range" min="1" max="5" value="3"></label></div>`).join('');function scoreDecision(){const vals=[...document.querySelectorAll('.slider input')].map(x=>+x.value);document.querySelectorAll('.slider output').forEach((o,i)=>o.textContent=vals[i]);const score=vals[0]+vals[1]+(6-vals[2])+(6-vals[3]);document.querySelector('#decisionScore').textContent=score+'/20';document.querySelector('#decisionAdvice').textContent=score>=16?'强烈信号：在确认好完整承诺后，可以考虑明确地表达同意。':score>=11?'中性信号：了解更多细节、协商工作范围，或先等待 24 小时再做决定。':'保护空间：这可能需要深思熟虑地拒绝、授权他人或“暂缓考虑”。'}document.querySelectorAll('.slider input').forEach(x=>x.oninput=scoreDecision);scoreDecision();
const waves={学习:'钻研这项手艺。寻找榜样、导师、刻意练习以及基础经验。',创造:'将你的所知转化为有用的产出。分享想法、原型、服务或艺术创作。',链接:'深耕并贡献于少数几个社区。在产生需求之前，建立真诚的双向关系。',收获:'接受累积工作带来的回报——收入、影响力或选择权——然后规划你的下一个学习周期。'};document.querySelector('#waveTool').innerHTML=Object.keys(waves).map(w=>`<button>${w}</button>`).join('');document.querySelectorAll('#waveTool button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#waveTool button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#waveAdvice').textContent=waves[b.textContent]});
function renderKeys(q=''){const s=q.toLowerCase();document.querySelector('#keyGrid').innerHTML=keys.filter(k=>(k.title+' '+k.text+' '+k.tag).toLowerCase().includes(s)).map(k=>`<article class="key-card"><span>${k.tag}</span><h3>${k.title}</h3><p>${k.text}</p></article>`).join('')||'<p>没有找到匹配项。请尝试更宽泛的关键词。</p>'}document.querySelector('#searchInput').oninput=e=>renderKeys(e.target.value);
const questions=[{q:'以下哪项最能代表长期思维？',a:['完美预测一个固定的未来','明确方向，并通过微型尝试不断学习','永远保持所有选项敞开'],correct:1,why:'长远的视野与灵活性并不冲突：明确的方向加上持续的实验，才能创造出更多选择。'},{q:'“20% 时间”的真正目的是什么？',a:['多承担 20% 的工作量','保证做一个能盈利的副业项目','保护一部分精力用于低风险的探索'],correct:2,why:'核心在于开展有边界、有意义的实验，而不是追求有保证的结果或增加额外负担。'},{q:'以下哪项属于“无限视野社交”？',a:['认识一位有趣的人，而不期待任何即时回报','为了紧急的推荐去联系一位陌生人','收集尽可能多的名片人脉'],correct:0,why:'它源于对人本身真诚的兴趣，没有任何功利性的诉求。'},{q:'当一条路线遭遇失败后，应该怎么做？',a:['立刻放弃原定的目标','隐瞒这次失败尝试','汲取经验教训，测试另一条路径'],correct:2,why:'具体路线可能会失败，但宏观的大方向依然可以是正确的。'}];let qi=0,qs=0;function renderQuiz(){const box=document.querySelector('#quizBox');if(qi>=questions.length){box.innerHTML=`<h3>你答对了 ${qs} / ${questions.length} 道题</h3><p>${qs===questions.length?'非常棒的理解！现在选择一个想法付诸实践吧。':'回顾一下不太熟悉的模块，然后再试一次。'}</p><button class="button primary" id="again">再试一次</button>`;document.querySelector('#again').onclick=()=>{qi=0;qs=0;renderQuiz()};return}const x=questions[qi];box.innerHTML=`<p class="eyebrow">问题 ${qi+1} / ${questions.length}</p><h3>${x.q}</h3><div class="quiz-options">${x.a.map((a,i)=>`<button data-i="${i}">${a}</button>`).join('')}</div><div class="feedback" aria-live="polite"></div>`;box.querySelectorAll('.quiz-options button').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===x.correct;if(ok)qs++;box.querySelector('.feedback').innerHTML=`${ok?'✓ 回答正确。':'不太准确。'} ${x.why} <button class="button ghost" id="continue">继续</button>`;box.querySelectorAll('.quiz-options button').forEach(x=>x.disabled=true);document.querySelector('#continue').onclick=()=>{qi++;renderQuiz()}})}
const steps=['预留 20 分钟不被打扰的时间用于思考。','拒绝或推迟一项低价值的请求。','写下三件你真正感到好奇的事物。','在日历上安排一次微型实验。','明确你当前的浪潮阶段：学习、创造、链接或收获。','将一项重复性的任务转化为可复用的模板。','向一位有趣的人发送一封表达赏识的邮件（不含任何请求）。','记录一个微小的成长“雨滴”进展。','给一个令人沮丧的结果换个新名字：实验数据。','花 5 分钟朝着对你重要的目标迈出一小步。'];const quick=document.querySelector('#quickDialog');document.querySelector('#quickBtn').onclick=()=>{document.querySelector('#quickStep').textContent=steps[Math.floor(Math.random()*steps.length)];quick.showModal()};document.querySelector('#closeQuick').onclick=()=>quick.close();
const clean=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function printAnswer(key){const value=(state.notes[key]||'').trim();return `<div class="print-answer ${value?'':'empty'}">${value?clean(value):'请在此处留下你的思考…'}</div>`}
function buildPrintView(){
  document.querySelectorAll('[data-note]').forEach(el=>state.notes[el.dataset.note]=el.value);
  save();
  const selectedWave=document.querySelector('#waveTool button.active')?.textContent||'';
  const moduleNotes=modules.filter(m=>(state.notes['module-'+m.id]||'').trim()).map(m=>`<article class="print-reflection"><h3>${String(m.id).padStart(2,'0')} · ${m.title}</h3><p class="print-prompt">${m.prompt}</p>${printAnswer('module-'+m.id)}</article>`).join('');
  document.querySelector('#printView').innerHTML=`<section class="print-cover"><p class="print-kicker">个人思考手册</p><h1>设计未来</h1><p class="print-lead">一份关于你所选择的方向、正在进行的实验以及下一步行动的实操记录。</p><p class="print-meta">生成时间：${new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'})}</p></section><section class="print-section"><h2>我的未来规划</h2><p class="print-section-intro">清晰的方向远比完美的预测更重要。</p><article class="print-entry"><h3>在未来的 5–10 年里，我希望获得更多…</h3>${printAnswer('direction')}</article><article class="print-entry"><h3>未来 90 天的核心优先事项</h3>${printAnswer('priority')}</article><article class="print-entry"><h3>我的下一个具体行动计划</h3>${printAnswer('next-step')}</article>${selectedWave?`<article class="print-entry"><h3>我当前所处的浪潮阶段</h3><div class="print-answer">${clean(selectedWave)}</div></article>`:''}</section><section class="print-section"><h2>我的 20% 实验</h2><p class="print-section-intro">微小的测试可以在不要求全力投入的前提下，带来宝贵的经验。</p><article class="print-entry"><h3>我感到好奇的事物</h3>${printAnswer('experiment')}</article><article class="print-entry"><h3>我可以执行的最小化测试</h3>${printAnswer('experiment-test')}</article><article class="print-entry"><h3>即便测试未达预期，我依然能收获什么</h3>${printAnswer('experiment-win')}</article></section>${moduleNotes?`<section class="print-section"><h2>模块思考记录</h2><p class="print-section-intro">在阅读本指南过程中记录的心得感悟。</p>${moduleNotes}</section>`:''}<div class="print-footer"><span>设计未来 · 个人实践手册</span><span>由 <a href="https://mindx.us/zh/">Mind X 社区</a> 开发</span></div>`;
}
window.addEventListener('beforeprint',buildPrintView);document.querySelector('#printBtn').onclick=()=>{buildPrintView();window.print()};document.querySelector('#menuBtn').onclick=e=>{const nav=document.querySelector('#nav');nav.classList.toggle('open');e.target.setAttribute('aria-expanded',nav.classList.contains('open'))};document.querySelectorAll('#nav a').forEach(a=>a.onclick=()=>document.querySelector('#nav').classList.remove('open'));
renderModules();renderKeys();renderQuiz();bindNotes();updateProgress();